language: java
jdk:
  - oraclejdk8

# Enable container-based architecture.
sudo: false

addons:
  apt:
    packages:
      # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
      # For native code tests, we need some additional libraries if we are in a 64-bit environment.
      - libgd2-xpm
      - ia32-libs
      - ia32-libs-multiarch
      - gcc-multilib

before_install:
  # Set up the Android environment.
  - export ANDROID_HOME=${HOME}/android-sdk-linux
  - ./scripts/travisci_install_android_sdk.sh

cache:
  directories:
    - $HOME/android-sdk-linux

script:
  - ./scripts/travisci_run.sh
